// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvrcchjbqumlknaboczh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2cmNjaGpicXVtbGtuYWJvY3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNjUxMDgsImV4cCI6MjA1MTg0MTEwOH0.F4Tyt3Ei2VYQiXoMdlRtLRF8gxMLeBfTVFOL32q3iYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);